import React from "react";
import { Github, Linkedin, Mail, ArrowUp, ExternalLink } from "lucide-react";

const projects = [
  {
    title: "Chronic Kidney Disorder Analysis Prediction",
    tag: "Machine Learning",
    description:
      "A machine learning project focused on analysing and predicting chronic kidney disorder.",
  },
  {
    title: "SkillNet Platform",
    tag: "Software Project",
    description:
      "A platform designed to exchange skills among individuals.",
  },
  {
    title: "Capturing Packets from a Web Page",
    tag: "Network Programming",
    description:
      "A network programming project focused on capturing packets generated by web-page activity.",
  },
];

function Navbar() {
  const links = ["home", "about", "academics", "projects", "contact"];

  return (
    <nav className="navbar">
      <a className="brand" href="#home">SG.</a>
      <div className="nav-links">
        {links.map((link) => (
          <a key={link} href={`#${link}`}>
            {link}
          </a>
        ))}
      </div>
    </nav>
  );
}

function Hero() {
  return (
    <section id="home" className="hero section">
      <div className="hero-content">
        <p className="eyebrow">WELCOME TO MY PORTFOLIO</p>
        <h1>
          Hi, I'm <span>Samyuktha G</span>
        </h1>
        <h2>Artificial Intelligence & Machine Learning Student</h2>
        <p className="hero-text">
          Passionate about technology and its applications in solving
          real-world problems.
        </p>
        <div className="hero-buttons">
          <a className="primary-btn" href="#projects">View My Projects</a>
          <a className="secondary-btn" href="#contact">Contact Me</a>
        </div>
      </div>

      <div className="hero-image-wrap">
        <div className="blob"></div>
        <img src="/photo.jpg" alt="Samyuktha G profile" className="profile-image" />
      </div>
    </section>
  );
}

function About() {
  return (
    <section id="about" className="section">
      <div className="section-heading">
        <p className="eyebrow">GET TO KNOW ME</p>
        <h2>About Me</h2>
      </div>

      <div className="about-card glass-card">
        <div className="about-icon">AI</div>
        <div>
          <p>
            Hi, I'm Samyuktha G, an Artificial Intelligence and Machine
            Learning student at Coimbatore Institute of Technology.
          </p>
          <p>
            I am interested in technology and its applications in solving
            real-world problems, and I aim to grow in AI/ML through learning
            and discipline.
          </p>
        </div>
      </div>
    </section>
  );
}

function Academics() {
  return (
    <section id="academics" className="section">
      <div className="section-heading">
        <p className="eyebrow">MY EDUCATION</p>
        <h2>Academics</h2>
      </div>

      <div className="academic-grid">
        <article className="academic-card">
          <span className="number">01</span>
          <h3>SSLC</h3>
          <strong>88%</strong>
          <p>10th Grade</p>
        </article>

        <article className="academic-card">
          <span className="number">02</span>
          <h3>HSC</h3>
          <strong>75%</strong>
          <p>12th Grade</p>
        </article>

        <article className="academic-card featured">
          <span className="number">03</span>
          <h3>M.Sc AI & ML</h3>
          <strong>7.5</strong>
          <p>Current CGPA</p>
        </article>
      </div>
    </section>
  );
}

function Projects() {
  return (
    <section id="projects" className="section">
      <div className="section-heading">
        <p className="eyebrow">WHAT I'VE BUILT</p>
        <h2>My Projects</h2>
      </div>

      <div className="project-grid">
        {projects.map((project, index) => (
          <article className="project-card" key={project.title}>
            <div className="project-top">
              <span className="project-number">0{index + 1}</span>
              <ExternalLink size={20} />
            </div>
            <span className="project-tag">{project.tag}</span>
            <h3>{project.title}</h3>
            <p>{project.description}</p>
            <a href="#contact" className="project-link">
              Learn more <span>→</span>
            </a>
          </article>
        ))}
      </div>
    </section>
  );
}

function Contact() {
  return (
    <section id="contact" className="section contact-section">
      <div className="contact-card">
        <div>
          <p className="eyebrow">LET'S CONNECT</p>
          <h2>Have an idea or opportunity?</h2>
          <p>
            I'm always interested in learning, building projects and exploring
            opportunities in technology.
          </p>
        </div>
        <a className="primary-btn" href="mailto:your-email@example.com">
          <Mail size={18} /> Get in Touch
        </a>
      </div>
    </section>
  );
}

function Footer() {
  return (
    <footer>
      <div>
        <strong>Samyuktha G</strong>
        <span>AI & ML Student</span>
      </div>
      <div className="socials">
        <a href="https://github.com/" target="_blank" rel="noreferrer" aria-label="GitHub">
          <Github size={19} />
        </a>
        <a href="https://linkedin.com/" target="_blank" rel="noreferrer" aria-label="LinkedIn">
          <Linkedin size={19} />
        </a>
        <a href="mailto:your-email@example.com" aria-label="Email">
          <Mail size={19} />
        </a>
      </div>
      <p>© {new Date().getFullYear()} Samyuktha G. All rights reserved.</p>
    </footer>
  );
}

function App() {
  return (
    <>
      <Navbar />
      <main>
        <Hero />
        <About />
        <Academics />
        <Projects />
        <Contact />
      </main>
      <Footer />
      <a className="back-top" href="#home" aria-label="Back to top">
        <ArrowUp size={18} />
      </a>
    </>
  );
}

export default App;